artistas = ['Leonardo Resende', 'Leonardo Resende', 'Cate Blanchett', 'Leonardo Davinci', 'Cate Blanchett', 'Adelia Machado', 'Leonardo Resende', 'Leonardo Resende', 'Leonardo Davinci', 'Leonardo Davinci', 'Nicole Kidman', 'Leonardo Resende', 'Nicole Kidman', 'Cate Blanchett', 'Nicole Kidman', 'Leonardo Davinci', 'Cate Blanchett', 'Leonardo Resende', 'Nicole Kidman', 'Adelia Machado', 'Adelia Machado', 'Cate Blanchett', 'Nicole Kidman', 'Leonardo Resende', 'Cate Blanchett', 'Cate Blanchett', 'Nicole Kidman', 'Cate Blanchett', 'Nicole Kidman', 'Cate Blanchett', 'Adelia Machado', 'Adelia Machado', 'Leonardo Davinci', 'Leonardo Resende', 'Cate Blanchett', 'Leonardo Resende', 'Nicole Kidman', 'Nicole Kidman', 'Nicole Kidman', 'Adelia Machado', 'Leonardo Davinci', 'Leonardo Resende', 'Leonardo Resende', 'Leonardo Resende', 'Adelia Machado', 'Adelia Machado', 'Cate Blanchett', 'Leonardo Davinci', 'Adelia Machado', 'Cate Blanchett', 'Nicole Kidman', 'Leonardo Davinci', 'Leonardo Davinci', 'Leonardo Resende', 'Adelia Machado', 'Cate Blanchett', 'Leonardo Resende', 'Cate Blanchett', 'Nicole Kidman', 'Cate Blanchett']
valor = [5480, 2540, 3425, 7668, 7668, 3408, 4544, 6850, 1270, 5964, 3425, 4795, 2840, 5931, 5680, 4544, 2032, 2286, 3976, 2540, 4544, 4544, 2840, 6590, 6816, 5964, 5931, 4795, 2286, 3295, 3295, 3954, 3954, 3295, 4260, 1524, 6816, 1778, 4260, 5680, 5480, 4544, 3425, 8520, 6590, 5931, 5680, 3408, 4795, 2540, 4795, 3295, 1524, 5480, 5964, 3976, 3295, 4110, 8520, 5480]
tipo_de_obra = ['Quadro', 'Escultura', 'Quadro', 'Quadro', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Quadro', 'Quadro', 'Quadro', 'Quadro', 'Quadro', 'Escultura', 'Quadro', 'Escultura', 'Quadro', 'Quadro', 'Quadro', 'Escultura', 'Quadro', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Quadro', 'Escultura', 'Quadro', 'Escultura', 'Escultura', 'Quadro', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Quadro', 'Escultura', 'Quadro', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Quadro', 'Escultura', 'Quadro', 'Escultura', 'Quadro', 'Quadro', 'Quadro', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura', 'Escultura']
obra = ['Romeu e Julieta', 'Mona Lisa', 'Hamlet', 'Romeu e Julieta', 'Mona Lisa', 'A noite estrelada', 'Romeu e Julieta', 'Romeu e Julieta', 'Mona Lisa', 'A noite estrelada', 'Mona Lisa', 'Mona Lisa', 'A noite estrelada', 'A noite estrelada', 'Mona Lisa', 'Quinta sinfonia', 'Mona Lisa', 'Hamlet', 'Hamlet', 'Mona Lisa', 'Dom Quixote', 'Dom Quixote', 'Hamlet', 'A noite estrelada', 'Dom Quixote', 'Mona Lisa', 'A noite estrelada', 'A noite estrelada', 'Romeu e Julieta', 'Mona Lisa', 'A noite estrelada', 'Hamlet', 'Romeu e Julieta', 'Mona Lisa', 'A noite estrelada', 'Quinta sinfonia', 'Hamlet', 'Romeu e Julieta', 'Mona Lisa', 'Mona Lisa', 'Dom Quixote', 'Hamlet', 'Dom Quixote', 'Hamlet', 'Dom Quixote', 'Romeu e Julieta', 'Dom Quixote', 'Hamlet', 'A noite estrelada', 'A noite estrelada', 'Dom Quixote', 'Romeu e Julieta', 'Romeu e Julieta', 'Romeu e Julieta', 'A noite estrelada', 'Hamlet', 'A noite estrelada', 'Hamlet', 'Quinta sinfonia', 'Quinta sinfonia']
lista_geral = []
for i in range(len(artistas)):
    agrupamento = (artistas[i].upper(), obra[i].upper(), valor[i], tipo_de_obra[i].upper())
    lista_geral.append(agrupamento)

print(lista_geral)