'''
1. Escreva um programa que receba como entrada os nomes de 60 obras da galeria e exiba o valor
total das obras do artista Leonardo da Vinci.
'''
teste1 = [["Mona Lisa", "Leonardo da Vinci", "Pintura"],
["A Noite Estrelada", "Vincente Van Gogh", "Pintura"],
["A Última Ceia", "Leonardo da Vinci", "Pintura"],
["O Nascimento de Vênus", "Sandro Botticelli", "Pintura"],
["Guernica", "Pablo Picasso", "Pintura"],
["O Beijo", "Gustav Klimt", "Pintura"],
["O Grito", "Edvard Munch", "Pintura"],
["A Persistência da Memória", "Salvador Dalí", "Pintura"],
["Os Girassóis", "Vincent van Gogh", "Pintura"],
["A Criação de Adão", "Michelangelo", "Pintura"],
["Os Lírios D'Água", "Claude Monet", "Pintura"],
["A Moça com o Brinco de Pérola", "Johannes Vermeer", "Pintura"],
["A Liberdade Guiando o Povo", "Eugène Delacroix", "Pintura"],
["Noite Estrelada sobre o Ródano", "Vincent van Gogh", "Pintura"],
["Auto-Retrato com Macaco", "Frida Kahlo", "Pintura"],
["O Gato e o Canário", "Franz Marc", "Pintura"],
["Os Meninos de Varberg", "Bruno Liljefors", "Pintura"],
["Crepúsculo", "Caspar David Friedrich", "Pintura"],
["Primavera", "Édouard Manet", "Pintura"],
["A Ronda Noturna", "Rembrandt", "Pintura"],
["A Persistência da Memória", "Salvador Dalí", "Pintura"],
["Nú de Costas", "Amedeo Modigliani", "Pintura"],
["Noite de Verão", "Edward Hopper", "Pintura"],
["O Filho do Homem", "René Magritte", "Pintura"],
["O Quarto de Van Gogh em Arles", "Vincent van Gogh", "Pintura"],
["Os Três Músicos", "Pablo Picasso", "Pintura"],
["O Nascimento de Cristo", "Sandro Botticelli", "Pintura"],
["Abaporu", "Tarsila do Amaral", "Pintura"],
["Nu Azul", "Henri Matisse", "Pintura"],
["Les Demoiselles d'Avignon", "Pablo Picasso", "Pintura"],
["Napoleão Cruzando os Alpes", "Jacques-Louis David", "Pintura"],
["Nenúfares", "Claude Monet", "Pintura"],
["A Última Ceia", "Tintoretto", "Pintura"],
["A Arte da Pintura", "Johannes Vermeer", "Pintura"],
["Auto-Retrato com Cachimbo", "Frida Kahlo", "Pintura"],
["O Lavrador de Café", "Candido Portinari", "Pintura"],
["La Grande Jatte", "Georges Seurat", "Pintura"],
["Moisés e os Dez Mandamentos", "Rembrandt", "Pintura"],
["Os Amantes", "René Magritte", "Pintura"],
["Cabeça de Medusa", "Caravaggio", "Escultura"],
["Primavera", "Sandro Botticelli", "Pintura"],
["O Guitarrista Cego", "Pablo Picasso", "Pintura"],
["Alegoria da Primavera", "Sandro Botticelli", "Pintura"],
["A Menina com um Brinco de Pérola", "Johannes Vermeer", "Pintura"],
["O Grito", "Edvard Munch", "Pintura"],
["Os Girassóis", "Vincent van Gogh", "Pintura"],
["O Gato", "Wassily Kandinsky", "Escultura"],
["O Banho Turco", "Jean-Auguste-Dominique Ingres", "Escultura"],
["Retrato de Adele Bloch-Bauer I", "Gustav Klimt", "Pintura"],
["Nenúfares e Ponte Japonesa", "Claude Monet", "Pintura"],
["O Beijo", "Gustav Klimt", "Pintura"],
["A Dama com Arminho", "Leonardo da Vinci", "Pintura"],
["As Meninas", "Diego Velázquez", "Escultura"],
["O Leão Moribundo", "Rosa Bonheur", "Escultura"],
["Guernica", "Pablo Picasso", "Pintura"],
["O Touro", "Pablo Picasso", "Escultura"],
["Dama Com Unicórnio", "Raphael", "Pintura"],
["Moça Lendo uma Carta à Luz de uma Janela Aberta", "Johannes Vermeer", "Pintura"],
["A Última Ceia", "Salvador Dalí", "Pintura"]]
